<center>Jaemin Son, 2018320192</center><br>

# Automatic Differentiation

In [1]:
import torch
from torch.autograd import Variable

# A Simple Example

In [2]:
x = Variable(torch.arange(4, dtype=torch.float32).reshape((4, 1)), requires_grad=True)
#Discussion : Variable function makes torch.tensor with more functions.
print(x)

tensor([[0.],
        [1.],
        [2.],
        [3.]], requires_grad=True)


In [3]:
y = 2*torch.mm(x.t(),x)
print(y)

tensor([[28.]], grad_fn=<MulBackward0>)


In [4]:
y.backward()

In [5]:
print("x.grad:", x.grad)
print("x.grad_fn", x.grad_fn) #Discussion : grad_fn of input is none.
print("y.grad_fn", y.grad_fn)

x.grad: tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])
x.grad_fn None
y.grad_fn <MulBackward0 object at 0x0000020C4CD3FF28>


In [6]:
print((x.grad - 4*x).norm().item() == 0)
print(x.grad)

True
tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])


In [7]:
print(x.grad - 4*x)

tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<SubBackward0>)


# Computing the Gradient of Python Control Flow

In [8]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [9]:
a = torch.randn(size=(1,))
print(a)
a.requires_grad = True
d = f(a)
print(d)
d.backward()

tensor([-0.5470])
tensor([-112020.4062], grad_fn=<MulBackward0>)


In [10]:
print(a.grad == (d / a))

tensor([True])


# Head gradients and the chain rule

In [11]:
x = Variable(torch.tensor([[0.],[1.],[2.],[3.]]), requires_grad=True)
y = x * 2
z = y * x

head_gradient = torch.tensor([[10], [1.], [.1], [.01]])
z.backward(head_gradient)
print(x.grad)

tensor([[0.0000],
        [4.0000],
        [0.8000],
        [0.1200]])


# Discussion
1. Variable function makes torch.tensor with more functions.
2. grad_fn of input is none.