<center>Jaemin Son, 2018320192</center><br>

# Getting Started

In [1]:
import torch
x = torch.arange(12, dtype=torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [2]:
x.shape

torch.Size([12])

In [3]:
x.size()

torch.Size([12])

In [4]:
x = x.reshape((3, 4))
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [5]:
x.reshape(-1)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [6]:
torch.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.Tensor(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x.dtype
#Discussion : torch.Tensor automatically sets dtype as torch.float32

torch.float32

In [9]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
torch.randn(3, 4)

tensor([[ 1.0964,  0.7018,  1.4894,  0.7753],
        [-0.5210,  0.2144,  0.6634, -0.6666],
        [ 0.0088, -0.3921, -0.6103, -0.0099]])

# Operations

In [14]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2
#Discussion : ones_like() makes a matrix with same size but filled with ones
print('x =', x)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = tensor([1., 2., 4., 8.])
x + y tensor([ 3.,  4.,  6., 10.])
x - y tensor([-1.,  0.,  2.,  6.])
x * y tensor([ 2.,  4.,  8., 16.])
x / y tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
print(x.dtype)
print(y)
torch.mm(x, y.t())
#Discussion : t() makes transpose matrix

torch.float32
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])

In [17]:
torch.dot(x.reshape(-1), y.reshape(-1))
#Discussion : torch.dot() requires one-dimensional vector

tensor(168.)

In [18]:
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [19]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [20]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
x.sum()

tensor(66.)

In [22]:
import numpy as np
np.asscalar(x.norm())

c:\users\jasson31\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  


22.494443893432617

# Broadcast Mechanism

In [23]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a, b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

In [24]:
a + b

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

# Indexing and Slicing

In [25]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# Saving Memory

In [28]:
before = id(y)
y = y + x
id(y) == before

False

In [29]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2782505350704
id(z): 2782505350704


In [30]:
before = id(z)
torch.add(x, y, out=z)
id(z) == before

True

# Mutual Transformation of PyTorch and NumPy

In [31]:
a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


# Discussion
1. torch.Tensor automatically sets dtype as torch.float32
2. ones_like() makes a matrix with same size but filled with ones
3. t() makes transpose matrix
4. torch.dot() requires one-dimensional vector